language: php
php:
- 5.3
- 5.4
- 5.5
- 5.6
- 7
- 7.1
- hhvm
matrix:
  allow_failures:
  - php: 7
  - php: 7.1
  - php: hhvm
sudo: false
before_script:
- travis_retry composer self-update
- npm install -g grunt-cli
- npm install
script:
- grunt lint --force
