language: php
matrix:
  allow_failures:
  - php: 7.0
  - php: 7.1
  - php: 7.2
  include:
  - php: 5.3
    dist: precise
  - php: 5.4
    dist: trusty
  - php: 5.5
    dist: trusty
  - php: 5.6
    dist: trusty
  - php: 7.0
    dist: trusty
  - php: 7.1
    dist: trusty
  - php: 7.2
    dist: trusty
sudo: false
before_script:
- travis_retry composer self-update
- npm install -g grunt-cli
- npm install
script:
- grunt lint --force
- grunt minify
